#!/bin/bash

top_path=../../../
cxxtestplus_path=${top_path}/3rdparty/cxxtestplus/src
OS_NAME=`uname`
if test "x$OS_NAME" = xDarwin; then
   export DYLD_LIBRARY_PATH=`cd ${top_path}/src/.libs && pwd`:$DYLD_LIBRARY_PATH
fi

cxxtestplus_path=../../../3rdparty/cxxtestplus/src

all_tests=`ls *.la`

${cxxtestplus_path}/runner/cxxtestplus-runner ${all_tests} \
    -L${cxxtestplus_path}/listeners -l"cxxtestplus_stdout_listener -c" -c10 $* 

