#!/bin/bash

OS_NAME=`uname`
if test "x$OS_NAME" = xDarwin; then
   export DYLD_LIBRARY_PATH=`cd ../src/.libs && pwd`:$DYLD_LIBRARY_PATH
fi

all_tests=`ls libmockcpp-ut?.la`

../3rdparty/cxxtestplus/src/runner/cxxtestplus-runner ${all_tests} \
    -L../3rdparty/cxxtestplus/src/listeners -l"cxxtestplus_stdout_listener -c" -c10 $* 

